apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent
  namespace: operational-load-exporter
data:
  agent.yaml: |
    metrics:
      global:
        scrape_interval: 300s
      configs:
      - name: operational-load-exporter
        remote_write:
        - url: {{ .Values.cortex.url }}
          basic_auth:
            username: {{ .Values.cortex.username }}
            password: {{ .Values.cortex.password }}
        scrape_configs:
        - job_name: operational-load-exporter
          static_configs:
            - targets: ["localhost:8000"]
