apiVersion: apps/v1
kind: Deployment
metadata:
  name: operational-load-exporter
  namespace: operational-load-exporter
  labels:
    app: operational-load-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operational-load-exporter
  template:
    metadata:
      labels:
        app: operational-load-exporter
    spec:
      containers:
      - name: operational-load-exporter
        image: quay.io/giantswarm/operational-load-exporter:{{ .Chart.Version }}
        resources: {{ .Values.resources.main }}
        env:
        - name: GITHUB_KEY
          valueFrom:
            secretKeyRef:
              name: operational-load-exporter
              key: GITHUB_KEY
              optional: false
        - name: INCIDENT_IO_KEY
          valueFrom:
            secretKeyRef:
              name: operational-load-exporter
              key: INCIDENT_IO_KEY
              optional: false
        - name: OPSGENIE_KEY
          valueFrom:
            secretKeyRef:
              name: operational-load-exporter
              key: OPSGENIE_KEY
              optional: false
      - name: grafana-agent
        image: grafana/agent:v0.25.0
        resources: {{ .Values.resources.grafana-agent }}
        args:
        - -config.file=/etc/agent/agent.yaml
        - -server.http.address=0.0.0.0:8001
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: grafana-agent
          mountPath: /etc/agent
        - name: agent-wal
          mountPath: /tmp/wal
      serviceAccountName: operational-load-exporter
      volumes:
      - name: grafana-agent
        configMap:
          name: grafana-agent
      - name: agent-wal
        emptyDir: {}
