apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: operational-load-exporter
  namespace: operational-load-exporter
spec:
  fsGroup:
    rule: RunAsAny
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operational-load-exporter
  namespace: operational-load-exporter
rules:
- apiGroups:
  - policy
  resourceNames:
  - operational-load-exporter
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operational-load-exporter
  namespace: operational-load-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operational-load-exporter
subjects:
- kind: ServiceAccount
  name: operational-load-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operational-load-exporter
  namespace: operational-load-exporter
