cortex:
  url: "DUMMY_VALUE"
  username: "DUMMY_VALUE"
  password: "DUMMY_VALUE"

github:
  key: "DUMMY_VALUE"

incidentio:
  key: "DUMMY_VALUE"

opsgenie:
  key: "DUMMY_VALUE"

resources:
  main:
    requests:
      cpu: 2m
      memory: 20Mi
    limits:
      cpu: 50m
      memory: 200Mi
  grafanaAgent:
    requests:
      cpu: 8m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 200Mi

global:
  podSecurityStandards:
    enforced: false
