version: 2.1
orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  build:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: operational-load-exporter
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-operational-load-exporter-to-quay
          image: "quay.io/giantswarm/operational-load-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          requires:
            - push-operational-load-exporter-to-quay
          name: push-to-app-catalog
          executor: app-build-suite
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "operational-load-exporter"
          filters:
            tags:
              only: /^v.*/
